--- 
- name: copy jar file to tomcat.
  hosts: dev 
  gather_facts: false  
  become: true
  tasks:
    - name: copy jar file to tomcat.
      copy:
        src: /var/lib/jenkins/workspace/job2/target/spring-petclinic-2.4.5.jar
        dest: /opt/apache-tomcat-9.0.46/webapps